[profile.default]
src = "contracts"
out = "out"
test = "test"
libs = ["lib"]

# Compiler
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = false
remappings = [
  "forge-std/=lib/forge-std/src/",
  "@openzeppelin/=lib/openzeppelin-contracts/"
]

# EVM config
# evm_version = "paris"

[fmt]
line_length = 100
multiline_func_header = "params_first"
